services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - AWS_EXECUTION_ENV=True
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,dynamodb,lambda,apigateway,cognito,sns,ses,route53,codepipeline,codebuild
    volumes:
      - './volume:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'